##For this assessment, we’ll use the breeding bird phenology from Hällfors et al. (2020a). Their data are on [Dryad](https://datadryad.org/stash/dataset/doi:10.5061/dryad.wstqjq2ht) (Hällfors et al. 2020b). We’ll complement that with the AVONET (Tobias et al. 2022) database of bird functional traits, which is on [Figshare](https://figshare.com/s/b990722d72a26b5bfead).

##Download the Dryad dataset. Copy “73_species.csv” and “Traits_73_species.csv” to your data/ folder.

```download.file("https://datadryad.org/stash/downloads/file_stream/382103",
              "data/73_species.csv")
              
download.file("https://datadryad.org/stash/downloads/file_stream/382102",
              "data/Traits_73_species.csv")```

##From the AVONET database on Figshare, download “AVONET Supplementary dataset 1.xlsx” do your data/ folder.

```download.file("https://figshare.com/ndownloader/files/34480856?private_link=b990722d72a26b5bfead",
              "data/AVONET_Supplementary_dataset_1.xlsx")```
              

              

#Load packages
library(tidyverse)
library(readxl)

#Read Data
bor_nestlings <- read_csv("data/73_species.csv")

bor_traits <- read_csv("data/Traits_73_species.csv")

avonet <- readxl::read_excel("data/AVONET_Supplementary_dataset_1.xlsx", sheet = 2) #only read sheet 2

#Explore
##all birds
all_birds_trend <- bor_nestlings %>% 
  group_by(Year) %>% 
  summarize(mean_doy = mean(Dayofyear))

ggplot(all_birds_trend, aes(Year, mean_doy)) + 
  geom_point() +
  geom_smooth(method = "lm")

##species trends
species_trends <- bor_nestlings %>% 
  group_by(Year, Species) %>% 
  summarize(mean_doy = mean(Dayofyear),
            .groups = "drop")
            
ggplot(species_trends, aes(Year, mean_doy, color = Species)) + 
  geom_point() +
  geom_smooth(method = "lm")
  
  
##most data-rich species            
data_richness <- bor_nestlings %>% 
  count(Species)

most_rich <- data_richness %>% 
  arrange(desc(n)) %>% 
  slice(1:5)

most_rich_trends <- bor_nestlings %>% 
  filter(Species %in% most_rich$Species) %>% 
  group_by(Species, Year) %>% 
  summarize(mean_doy = mean(Dayofyear), 
            .groups = "drop")

ggplot(most_rich_trends, aes(Year, mean_doy, color = Species)) +
  geom_point() +
  geom_smooth(method = "lm")
            
ggplot(species_trends, aes(Year, mean_doy, color = Species)) + 
  geom_point() +
  geom_smooth(method = "lm")
  
# I'm giving you a *function* to help here. You'll learn more about those next week.

## Finds the slope of the relationship between y and x
trend <- function(x, y) {
  xy_lm <- lm(y ~ x)
  coef(xy_lm)[2]
}

##define bor_by_year
bor_by_year <- bor_nestlings %>% 
  group_by(Year, Species) %>% 
  summarize(mean_doy = mean(Dayofyear)) %>% 
  view()

## Calculate the trend for all species
bor_trends <- bor_by_year %>%
  group_by(Species) %>% 
  summarize(doy_trend = trend(Year, mean_doy))
            
```bor_by_year not currently defined-- what do we mean here...?```

soi <- c("ARDCIN", "LARMIN")
bor_by_year %>% 
  filter(Species %in% soi) %>% 
  ggplot(aes(Year, mean_doy, color = Species)) +
  geom_point() +
  geom_smooth(method = "lm")

nrow_bor_trends <- nrow(bor_trends) # Use this later

bor_extreme <- bor_trends %>% 
  ## Sort by the day of year trend
  arrange(doy_trend) %>% 
  ## Keep just the first (most negative trend) and last (most positive trend) rows
  slice(c(1, nrow_bor_trends))

## Now plot them
bor_by_year %>% 
  filter(Species %in% bor_extreme$Species) %>% 
  ggplot(aes(Year, mean_doy, color = Species)) + 
    geom_point() +
    geom_smooth(method = "lm")

# Bring in more data
## First, select and rename important columns
avonet_size <- select(avonet, SciName = Species1, Mass_g = Mass)
bor_sciname <- select(bor_traits, 
                      Species = Abbreviation, 
                      SciName = `Scientific name`)
  
## Join
bor_trends_size <- bor_trends %>% 
  left_join(bor_sciname, bor_trends, by = "Species") %>% 
  left_join(avonet_size, bor_trends, by = "SciName") %>% 
  mutate(abs_trend = abs(doy_trend)) %>% 
  view()
  

## Plot it
ggplot(bor_trends_size, aes(Mass_g, abs_trend)) +
  geom_point() +
  geom_smooth(method = "lm")
  
##  Make a new variable, bor_trends_size2, that removes the missing values in Mass_g and keeps only birds smaller than 2000 g with an absolute trend less than 1.

bor_trends_size2 <- bor_trends_size %>% 
  drop_na(Mass_g) %>% 
  filter(Mass_g < 2000, abs_trend < 1) %>% 
  view()
  
  
ggplot(bor_trends_size2, aes(Mass_g, abs_trend)) +
  geom_point() +
  geom_smooth(method = "lm")
  
##Hypothesis evaluation
The second trend size graph does *not* indicate a strong relationship between mass and trend. However, the birds larger than 2000 g indicate a negative trend. I also would like to review why we are using absolute trends.
    